import type { MetadataRoute } from 'next';

// Allow public landing pages; lock everything operator-facing.
// Sitemap auto-generated by src/app/sitemap.ts.

export default function robots(): MetadataRoute.Robots {
  const base = (process.env.NEXT_PUBLIC_APP_URL || 'https://app.limeinc.cc').replace(/\/$/, '');
  return {
    rules: [
      {
        userAgent: '*',
        allow: ['/stay/', '/dine/', '/r/'],
        disallow: [
          '/admin/',
          '/beithady/',
          '/fmplus/',
          '/api/',
          '/account/',
          '/login',
          '/g/',
          '/personal/',
          '/emails/',
        ],
      },
    ],
    sitemap: `${base}/sitemap.xml`,
  };
}
