/**
 * PDF Footer — rendered at the bottom of every page via fixed element.
 * Shows: "Generated by {name} · {date} · Page N of M"
 */
import React from 'react';
import { View, Text } from '@react-pdf/renderer';
import { PDF_THEME } from '../theme';

interface PdfFooterProps {
  generatedBy: string;
  generatedAt: string; // ISO string
}

function fmtDate(iso: string): string {
  try {
    return new Date(iso).toLocaleDateString('en-GB', {
      day: '2-digit',
      month: 'short',
      year: 'numeric',
    });
  } catch {
    return iso;
  }
}

export function PdfFooter({ generatedBy, generatedAt }: PdfFooterProps) {
  const dateLabel = fmtDate(generatedAt);

  return (
    <View
      fixed
      style={{
        position: 'absolute',
        bottom: 16,
        left: 32,
        right: 32,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderTop: `0.5px solid ${PDF_THEME.colors.greyLight}`,
        paddingTop: 4,
      }}
    >
      <Text style={{ fontSize: 6, color: PDF_THEME.colors.textMuted, fontFamily: 'Helvetica' }}>
        Generated by {generatedBy} · {dateLabel}
      </Text>
      <Text
        style={{ fontSize: 6, color: PDF_THEME.colors.textMuted, fontFamily: 'Helvetica' }}
        render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`}
      />
    </View>
  );
}
