-- =====================================================================
-- Beithady v2 — Phase H: Ads module (port from VoltAuto)
-- =====================================================================
-- Mirrors the proven VoltAuto ads architecture (C:\Voltauto-pricing\
-- supabase\migrations\20260418_ads_module.sql) with Beithady-specific
-- extensions:
--   - campaigns gain building_codes[] (which BH-* the campaign promotes)
--   - ad_sets gain target_countries[] + target_interests[] (CRM Market
--     Intelligence drives this)
--   - ads gain gallery_asset_ids[] (Phase D's beithady_gallery_assets
--     marked ad_eligible feed the carousel creatives)
--   - leads gain building_interest + matched_reservation_id for the
--     ad-to-booking attribution trigger
--
-- Three views ported verbatim plus one Beithady extension
-- (ads_lead_funnel JOINs guesty_reservations for attribution status).

-- 1. Ad accounts — one row per (platform, external ad-account id)
create table if not exists public.ads_accounts (
  id                       bigint generated by default as identity primary key,
  platform                 text not null check (platform in ('meta','google','tiktok')),
  external_id              text not null,
  name                     text not null,
  currency                 text not null default 'USD',
  timezone                 text not null default 'Africa/Cairo',
  status                   text not null default 'active' check (status in ('active','paused','archived')),
  meta_business_id         text,
  meta_app_id              text,
  fb_page_id               text,                                  -- Facebook page used for CTWA + creatives
  google_login_customer_id text,
  notes                    text default '',
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now(),
  unique (platform, external_id)
);

-- 2. Campaigns
create table if not exists public.ads_campaigns (
  id                     bigint generated by default as identity primary key,
  account_id             bigint not null references public.ads_accounts(id) on delete cascade,
  platform               text not null check (platform in ('meta','google','tiktok')),
  external_id            text not null,
  name                   text not null,
  status                 text,
  objective              text,
  buying_type            text,
  daily_budget_micros    bigint,
  lifetime_budget_micros bigint,
  start_time             timestamptz,
  end_time               timestamptz,
  -- Beithady extension: which BH-* buildings this campaign promotes
  building_codes         text[],
  raw                    jsonb,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  unique (platform, external_id)
);
create index if not exists idx_ads_campaigns_account on public.ads_campaigns(account_id);
create index if not exists idx_ads_campaigns_status on public.ads_campaigns(status);
create index if not exists idx_ads_campaigns_buildings on public.ads_campaigns using gin(building_codes);

-- 3. Ad sets
create table if not exists public.ads_ad_sets (
  id                  bigint generated by default as identity primary key,
  campaign_id         bigint not null references public.ads_campaigns(id) on delete cascade,
  platform            text not null check (platform in ('meta','google','tiktok')),
  external_id         text not null,
  name                text not null,
  status              text,
  optimization_goal   text,
  daily_budget_micros bigint,
  targeting           jsonb,
  -- Beithady extensions: country/interest targeting from market intel
  target_countries    text[],
  target_interests    text[],
  age_min             int,
  age_max             int,
  raw                 jsonb,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  unique (platform, external_id)
);
create index if not exists idx_ads_adsets_campaign on public.ads_ad_sets(campaign_id);
create index if not exists idx_ads_adsets_countries on public.ads_ad_sets using gin(target_countries);

-- 4. Ads (creatives)
create table if not exists public.ads_ads (
  id                bigint generated by default as identity primary key,
  ad_set_id         bigint not null references public.ads_ad_sets(id) on delete cascade,
  platform          text not null check (platform in ('meta','google','tiktok')),
  external_id       text not null,
  name              text not null,
  status            text,
  creative_type     text,
  creative_url      text,
  headline          text,
  body              text,
  cta               text,
  landing_url       text,
  -- Beithady extension: which gallery assets feed this carousel
  gallery_asset_ids uuid[],
  -- AI-copy provenance
  ai_copy_log_id    uuid,
  language          text,
  utm_source        text,
  utm_medium        text,
  utm_campaign      text,
  utm_content       text,
  utm_term          text,
  raw               jsonb,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  unique (platform, external_id)
);
create index if not exists idx_ads_ads_adset on public.ads_ads(ad_set_id);
create index if not exists idx_ads_ads_gallery on public.ads_ads using gin(gallery_asset_ids);

-- 5. Daily metrics rollup
create table if not exists public.ads_daily_metrics (
  id                       bigint generated by default as identity primary key,
  account_id               bigint not null references public.ads_accounts(id) on delete cascade,
  campaign_id              bigint not null references public.ads_campaigns(id) on delete cascade,
  ad_set_id                bigint references public.ads_ad_sets(id) on delete cascade,
  ad_id                    bigint references public.ads_ads(id) on delete cascade,
  platform                 text not null check (platform in ('meta','google','tiktok')),
  metric_date              date not null,
  impressions              bigint default 0,
  clicks                   bigint default 0,
  spend_micros             bigint default 0,
  reach                    bigint,
  leads                    bigint default 0,
  conversions              bigint default 0,
  conversion_value_micros  bigint default 0,
  video_views              bigint,
  raw                      jsonb,
  synced_at                timestamptz not null default now()
);
create unique index if not exists ads_daily_metrics_ad_day_uk      on public.ads_daily_metrics(ad_id, metric_date)      where ad_id is not null;
create unique index if not exists ads_daily_metrics_set_day_uk     on public.ads_daily_metrics(ad_set_id, metric_date)  where ad_id is null and ad_set_id is not null;
create unique index if not exists ads_daily_metrics_campaign_day_uk on public.ads_daily_metrics(campaign_id, metric_date) where ad_id is null and ad_set_id is null;
create index if not exists ads_daily_metrics_date_idx          on public.ads_daily_metrics(metric_date desc);
create index if not exists ads_daily_metrics_campaign_date_idx on public.ads_daily_metrics(campaign_id, metric_date desc);

-- 6. Leads (CTWA + lead form ingests)
create table if not exists public.ads_leads (
  id                     bigint generated by default as identity primary key,
  platform               text not null default 'meta' check (platform in ('meta','google','tiktok')),
  external_id            text not null,
  ad_id                  bigint references public.ads_ads(id) on delete set null,
  ad_set_id              bigint references public.ads_ad_sets(id) on delete set null,
  campaign_id            bigint references public.ads_campaigns(id) on delete set null,
  form_id                text,
  form_name              text,
  full_name              text,
  phone_raw              text,
  phone_e164             text,
  email                  text,
  -- Beithady extension: which building/country the lead asked about
  building_interest      text,
  country                text,
  language               text,
  travel_dates           jsonb,                                  -- { check_in, check_out, nights }
  consent_granted        boolean not null default false,
  consent_text_version   text,
  consent_granted_at     timestamptz,
  raw_payload            jsonb not null,
  -- Beithady extensions: link to CRM + attribution
  beithady_guest_id      uuid references public.beithady_guests(id) on delete set null,
  matched_reservation_id text,                                   -- guesty_reservations.id when attributed
  matched_at             timestamptz,
  processed_at           timestamptz,
  error                  text,
  created_at             timestamptz not null default now(),
  unique (platform, external_id)
);
create index if not exists ads_leads_phone_idx     on public.ads_leads(phone_e164);
create index if not exists ads_leads_campaign_idx  on public.ads_leads(campaign_id);
create index if not exists ads_leads_processed_idx on public.ads_leads(processed_at);
create index if not exists ads_leads_created_idx   on public.ads_leads(created_at desc);
create index if not exists ads_leads_matched_idx   on public.ads_leads(matched_reservation_id) where matched_reservation_id is not null;

-- 7. Sync run log
create table if not exists public.ads_sync_log (
  id              bigint generated by default as identity primary key,
  job_name        text not null,
  platform        text not null check (platform in ('meta','google','tiktok')),
  started_at      timestamptz not null default now(),
  finished_at     timestamptz,
  status          text not null default 'running' check (status in ('running','success','error','partial')),
  rows_upserted   integer default 0,
  leads_ingested  integer default 0,
  spend_synced    numeric(14,2),
  error           text,
  details         jsonb
);
create index if not exists ads_sync_log_recent_idx on public.ads_sync_log(started_at desc);

-- 8. AI copy generation log
create table if not exists public.beithady_ads_ai_copy_log (
  id              uuid primary key default gen_random_uuid(),
  campaign_id     bigint references public.ads_campaigns(id) on delete cascade,
  language        text not null default 'en',
  variant         int not null,
  headline        text,
  primary_text    text,
  cta             text,
  prompt_version  text default 'v1',
  model           text default 'claude-haiku-4-5',
  raw             jsonb,
  generated_at    timestamptz not null default now()
);
create index if not exists idx_bh_ads_copy_campaign on public.beithady_ads_ai_copy_log(campaign_id);

-- =====================================================================
-- 9. RLS — open by default (single-tenant); admin gates upstream
-- =====================================================================
alter table public.ads_accounts          enable row level security;
alter table public.ads_campaigns         enable row level security;
alter table public.ads_ad_sets           enable row level security;
alter table public.ads_ads               enable row level security;
alter table public.ads_daily_metrics     enable row level security;
alter table public.ads_leads             enable row level security;
alter table public.ads_sync_log          enable row level security;
alter table public.beithady_ads_ai_copy_log enable row level security;

do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='ads_accounts'      and policyname='ads_accounts_all')      then create policy ads_accounts_all      on public.ads_accounts      for all using (true) with check (true); end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='ads_campaigns'     and policyname='ads_campaigns_all')     then create policy ads_campaigns_all     on public.ads_campaigns     for all using (true) with check (true); end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='ads_ad_sets'       and policyname='ads_ad_sets_all')       then create policy ads_ad_sets_all       on public.ads_ad_sets       for all using (true) with check (true); end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='ads_ads'           and policyname='ads_ads_all')           then create policy ads_ads_all           on public.ads_ads           for all using (true) with check (true); end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='ads_daily_metrics' and policyname='ads_daily_metrics_all') then create policy ads_daily_metrics_all on public.ads_daily_metrics for all using (true) with check (true); end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='ads_leads'         and policyname='ads_leads_all')         then create policy ads_leads_all         on public.ads_leads         for all using (true) with check (true); end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='ads_sync_log'      and policyname='ads_sync_log_all')      then create policy ads_sync_log_all      on public.ads_sync_log      for all using (true) with check (true); end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='beithady_ads_ai_copy_log' and policyname='beithady_ads_ai_copy_log_all') then create policy beithady_ads_ai_copy_log_all on public.beithady_ads_ai_copy_log for all using (true) with check (true); end if;
end $$;

-- =====================================================================
-- 10. Views — analytics + lead funnel + Beithady ad-to-booking
-- =====================================================================

create or replace view public.ads_campaign_performance as
select
  c.id as campaign_id, c.name as campaign_name, c.platform,
  a.name as account_name, a.currency as account_currency,
  c.status as campaign_status, c.objective,
  c.building_codes,
  coalesce(sum(m.impressions),0) as impressions,
  coalesce(sum(m.clicks),0)      as clicks,
  coalesce(sum(m.spend_micros),0)/1000000.0 as spend,
  coalesce(sum(m.leads),0)       as leads,
  coalesce(sum(m.conversions),0) as conversions,
  case when sum(m.clicks)>0  then (sum(m.spend_micros)/1000000.0)/nullif(sum(m.clicks),0) end as cpc,
  case when sum(m.leads)>0   then (sum(m.spend_micros)/1000000.0)/nullif(sum(m.leads),0)  end as cpl,
  case when sum(m.impressions)>0 then 100.0*sum(m.clicks)::numeric/nullif(sum(m.impressions),0) end as ctr_pct,
  min(m.metric_date) as first_date, max(m.metric_date) as last_date
from public.ads_campaigns c
join public.ads_accounts a on a.id=c.account_id
left join public.ads_daily_metrics m on m.campaign_id=c.id and m.ad_id is null and m.ad_set_id is null
group by c.id, c.name, c.platform, a.name, a.currency, c.status, c.objective, c.building_codes;

create or replace view public.ads_overview_daily as
select m.metric_date, m.platform,
  sum(m.impressions) as impressions,
  sum(m.clicks)      as clicks,
  sum(m.spend_micros)/1000000.0 as spend,
  sum(m.leads)       as leads,
  case when sum(m.leads)>0 then (sum(m.spend_micros)/1000000.0)/nullif(sum(m.leads),0) end as cpl
from public.ads_daily_metrics m
where m.ad_id is null and m.ad_set_id is null
group by m.metric_date, m.platform
order by m.metric_date desc;

create or replace view public.ads_lead_funnel as
select
  l.id as lead_id,
  l.created_at,
  l.platform,
  l.campaign_id,
  cp.name as campaign_name,
  cp.building_codes,
  l.form_name,
  l.full_name,
  l.phone_e164,
  l.email,
  l.country,
  l.building_interest,
  l.beithady_guest_id,
  l.matched_reservation_id,
  l.matched_at,
  -- Booking attribution status
  case
    when l.matched_reservation_id is not null then 'booked'
    when l.processed_at is not null then 'processed'
    else 'new'
  end as funnel_stage,
  r.host_payout as booking_value,
  r.currency as booking_currency,
  r.check_in_date as booking_check_in
from public.ads_leads l
left join public.ads_campaigns cp on cp.id = l.campaign_id
left join public.guesty_reservations r on r.id = l.matched_reservation_id
order by l.created_at desc;

-- =====================================================================
-- 11. Attribution trigger — when a guesty_reservation lands and the
-- guest's phone matches an ads_lead from the past 90 days, link them.
-- =====================================================================

create or replace function public.beithady_ads_match_lead_to_reservation()
returns trigger language plpgsql as $$
declare
  guest_phone_e164 text;
begin
  if new.guest_phone is null then return new; end if;
  guest_phone_e164 := '+' || regexp_replace(coalesce(new.guest_phone, ''), '[^0-9]', '', 'g');
  if length(guest_phone_e164) < 10 then return new; end if;

  update public.ads_leads
     set matched_reservation_id = new.id,
         matched_at             = now()
   where phone_e164 = guest_phone_e164
     and matched_reservation_id is null
     and created_at > now() - interval '90 days'
     and (new.created_at_odoo is null or new.created_at_odoo > created_at);

  return new;
end $$;

drop trigger if exists ads_attribution_on_reservation on public.guesty_reservations;
create trigger ads_attribution_on_reservation
  after insert or update on public.guesty_reservations
  for each row execute function public.beithady_ads_match_lead_to_reservation();

-- =====================================================================
-- 12. Touch trigger
-- =====================================================================
do $$ declare t text; begin
  for t in select unnest(array['ads_accounts','ads_campaigns','ads_ad_sets','ads_ads']) loop
    execute format(
      'drop trigger if exists %I_touch on public.%I; create trigger %I_touch before update on public.%I for each row execute function public.beithady_guests_touch_updated();',
      t, t, t, t
    );
  end loop;
end $$;

insert into public.beithady_audit_log(module, action, metadata) values
  ('ads', 'phase_h_installed',
   jsonb_build_object('migration', '0040_beithady_ads', 'phase', 'H'));
