-- =====================================================================
-- Beithady — Phase H+: Multi-platform ads (Google + TikTok + Instagram + FB Reels)
-- =====================================================================
-- Extends Phase H (0040_beithady_ads.sql, Meta CTWA only) with:
--   - ads_accounts: extra columns for IG resolve, Google OAuth state,
--     TikTok BC + identity + refresh tokens
--   - ads_instagram_posts: organic IG Reels publish history (+ FB Reels cross-post)
--   - ads_tiktok_posts: organic TikTok publish history (inbox + direct-post flows)
--   - ads_leads: lead_source column (CTWA / lead_form / google_form / tiktok_form)
--
-- Ports the Voltauto reference (C:\Voltauto-pricing\supabase\migrations\
-- 20260424_ads_platform_add_tiktok.sql, 20260429_ads_instagram_publish.sql,
-- 20260430_ads_instagram_posts_add_fb_crosspost.sql,
-- 20260501_ads_tiktok_organic_publishing.sql) into one migration aligned
-- to Beithady's numbering scheme.

-- 1. ads_accounts extensions (all nullable, idempotent)
alter table public.ads_accounts add column if not exists fb_page_name              text;
alter table public.ads_accounts add column if not exists ig_business_id            text;
alter table public.ads_accounts add column if not exists ig_username               text;

alter table public.ads_accounts add column if not exists google_customer_id        text;        -- target operating customer (vs login_customer_id MCC)
alter table public.ads_accounts add column if not exists google_refresh_token      text;        -- AES-encrypted via src/lib/crypto.ts
alter table public.ads_accounts add column if not exists google_refresh_expires_at timestamptz;

alter table public.ads_accounts add column if not exists tiktok_advertiser_id      text;
alter table public.ads_accounts add column if not exists tiktok_bc_id              text;
alter table public.ads_accounts add column if not exists tiktok_identity_id        text;
alter table public.ads_accounts add column if not exists tiktok_identity_type      text;        -- CUSTOMIZED_USER | TT_USER | BC_AUTH_TT | UNAUTH_TT_USER
alter table public.ads_accounts add column if not exists tiktok_refresh_token      text;        -- AES-encrypted
alter table public.ads_accounts add column if not exists tiktok_open_id            text;
alter table public.ads_accounts add column if not exists tiktok_username           text;
alter table public.ads_accounts add column if not exists tiktok_token_expires_at   timestamptz;
alter table public.ads_accounts add column if not exists tiktok_refresh_expires_at timestamptz;

create index if not exists idx_ads_accounts_platform on public.ads_accounts(platform);

-- 2. ads_leads: lead_source for routing different lead-form types
alter table public.ads_leads add column if not exists lead_source text;          -- 'ctwa' | 'meta_lead_form' | 'google_lead_form' | 'tiktok_lead_form' | 'manual'
alter table public.ads_leads add column if not exists building_code text;        -- direct building ref (in addition to building_interest text)
create index if not exists ads_leads_lead_source_idx on public.ads_leads(lead_source);
create index if not exists ads_leads_building_code_idx on public.ads_leads(building_code) where building_code is not null;

-- 3. Instagram organic Reels history (+ FB cross-post tracking)
create table if not exists public.ads_instagram_posts (
  id                    bigint generated by default as identity primary key,
  ads_account_id        bigint not null references public.ads_accounts(id) on delete cascade,
  -- Source asset
  video_url             text not null,
  ads_gallery_item_id   uuid references public.beithady_gallery_assets(id) on delete set null,
  -- Copy
  caption               text,
  hashtags              text[],
  share_to_feed         boolean not null default true,
  -- Beithady extension: building attribution for analytics
  building_code         text,
  -- IG publish state machine
  container_id          text,
  media_id              text,
  permalink             text,
  thumbnail_url         text,
  status                text not null default 'PENDING_CREATE'
                          check (status in ('PENDING_CREATE','IN_PROGRESS','PUBLISHED','ERROR','EXPIRED')),
  status_error          text,
  -- Facebook Reels cross-post (best-effort, optional)
  fb_status             text check (fb_status in ('PENDING','PUBLISHED','ERROR','SKIPPED')),
  fb_page_post_id       text,
  fb_permalink          text,
  fb_published_at       timestamptz,
  fb_status_error       text,
  -- Audit
  created_by            text,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  published_at          timestamptz
);
create index if not exists ads_ig_posts_account_idx       on public.ads_instagram_posts(ads_account_id);
create index if not exists ads_ig_posts_status_idx        on public.ads_instagram_posts(status);
create index if not exists ads_ig_posts_created_at_idx    on public.ads_instagram_posts(created_at desc);
create index if not exists ads_ig_posts_building_code_idx on public.ads_instagram_posts(building_code) where building_code is not null;

-- 4. TikTok organic posts history
create table if not exists public.ads_tiktok_posts (
  id                              bigint generated by default as identity primary key,
  ads_account_id                  bigint not null references public.ads_accounts(id) on delete cascade,
  -- Source asset
  video_url                       text not null,
  ads_gallery_item_id             uuid references public.beithady_gallery_assets(id) on delete set null,
  -- Copy
  caption                         text,
  hashtags                        text[],
  privacy_level                   text not null default 'PUBLIC_TO_EVERYONE'
                                    check (privacy_level in ('PUBLIC_TO_EVERYONE','MUTUAL_FOLLOW_FRIENDS','SELF_ONLY','FOLLOWER_OF_CREATOR')),
  -- Beithady extension
  building_code                   text,
  -- TikTok publish state machine (Content Posting API)
  publish_id                      text,
  publicly_available_post_id      text,
  share_url                       text,
  status                          text not null default 'PENDING_CREATE'
                                    check (status in ('PENDING_CREATE','PROCESSING_UPLOAD','PROCESSING_DOWNLOAD','SEND_TO_USER_INBOX','PUBLISH_COMPLETE','FAILED','EXPIRED')),
  status_error                    text,
  -- Audit
  created_by                      text,
  created_at                      timestamptz not null default now(),
  updated_at                      timestamptz not null default now(),
  published_at                    timestamptz
);
create index if not exists ads_tt_posts_account_idx       on public.ads_tiktok_posts(ads_account_id);
create index if not exists ads_tt_posts_status_idx        on public.ads_tiktok_posts(status);
create index if not exists ads_tt_posts_created_at_idx    on public.ads_tiktok_posts(created_at desc);
create index if not exists ads_tt_posts_building_code_idx on public.ads_tiktok_posts(building_code) where building_code is not null;

-- 5. RLS — open by default (single-tenant; admin gates upstream via Beithady role/permission)
alter table public.ads_instagram_posts enable row level security;
alter table public.ads_tiktok_posts    enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='ads_instagram_posts' and policyname='ads_instagram_posts_all') then
    create policy ads_instagram_posts_all on public.ads_instagram_posts for all using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='ads_tiktok_posts' and policyname='ads_tiktok_posts_all') then
    create policy ads_tiktok_posts_all on public.ads_tiktok_posts for all using (true) with check (true);
  end if;
end $$;

-- 6. Touch triggers (reuse beithady_guests_touch_updated() from earlier migration)
do $$ declare t text; begin
  for t in select unnest(array['ads_instagram_posts','ads_tiktok_posts']) loop
    execute format(
      'drop trigger if exists %I_touch on public.%I; create trigger %I_touch before update on public.%I for each row execute function public.beithady_guests_touch_updated();',
      t, t, t, t
    );
  end loop;
end $$;

-- 7. Backfill lead_source for existing rows (assume all Phase H leads were CTWA)
update public.ads_leads
   set lead_source = 'ctwa'
 where lead_source is null;

-- 8. Extend ads_overview_daily / ads_campaign_performance: no-op (the existing
-- views already pivot by platform — Google + TikTok rows surface automatically
-- once campaigns sync). Documenting that here so future readers don't search
-- for a view change that was intentionally skipped.

-- 9. Audit
insert into public.beithady_audit_log(module, action, metadata) values
  ('ads', 'phase_h_multi_platform_installed',
   jsonb_build_object(
     'migration', '0103_bh_ads_multi_platform',
     'platforms', jsonb_build_array('meta','google','tiktok'),
     'new_tables', jsonb_build_array('ads_instagram_posts','ads_tiktok_posts'),
     'extends', jsonb_build_array('ads_accounts','ads_leads')
   ));
