-- Server-side conversion events for Meta CAPI + Google Offline + TikTok Events.
-- A row lands here every time we want to tell an ad platform "this lead
-- converted". Cron /api/cron/beithady-ads-conversions-flush sends the
-- pending rows and marks them sent. The DB-trigger fires this row on
-- ads_leads.matched_reservation_id transitioning from NULL → not-null
-- (i.e. when a booking is attributed to a lead).

create table if not exists public.ads_conversion_events_log (
  id              bigint generated by default as identity primary key,
  lead_id         bigint references public.ads_leads(id) on delete cascade,
  reservation_id  text,
  platform        text not null check (platform in ('meta','google','tiktok')),
  event_type      text not null check (event_type in ('Lead','Purchase','CompleteRegistration','InitiateCheckout')),
  event_id        text not null,
  event_time      timestamptz not null default now(),
  value_usd       numeric(14,2),
  currency        text,
  raw_payload     jsonb,
  status          text not null default 'pending' check (status in ('pending','sent','error','skipped')),
  response        jsonb,
  error           text,
  sent_at         timestamptz,
  created_at      timestamptz not null default now(),
  unique (platform, event_id)
);
create index if not exists idx_ads_conv_events_pending on public.ads_conversion_events_log(status, created_at) where status = 'pending';
create index if not exists idx_ads_conv_events_lead on public.ads_conversion_events_log(lead_id);

alter table public.ads_conversion_events_log enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='ads_conversion_events_log' and policyname='ads_conv_events_all') then
    create policy ads_conv_events_all on public.ads_conversion_events_log for all using (true) with check (true);
  end if;
end $$;

create or replace function public.queue_ads_conversion_on_match()
returns trigger language plpgsql as $$
declare
  guesty_value   numeric;
  guesty_curr    text;
  evt_id         text;
begin
  if new.matched_reservation_id is null then return new; end if;
  if old.matched_reservation_id is not null then return new; end if;

  select host_payout, currency
    into guesty_value, guesty_curr
    from public.guesty_reservations
   where id = new.matched_reservation_id
   limit 1;

  evt_id := 'lead_' || new.id || '_purchase';

  insert into public.ads_conversion_events_log
    (lead_id, reservation_id, platform, event_type, event_id, event_time, value_usd, currency)
  values
    (new.id, new.matched_reservation_id, new.platform, 'Purchase', evt_id, new.matched_at, guesty_value, guesty_curr)
  on conflict (platform, event_id) do nothing;

  return new;
end $$;

drop trigger if exists trg_queue_ads_conversion_on_match on public.ads_leads;
create trigger trg_queue_ads_conversion_on_match
  after update of matched_reservation_id on public.ads_leads
  for each row execute function public.queue_ads_conversion_on_match();

create or replace function public.queue_ads_conversion_on_new_lead()
returns trigger language plpgsql as $$
declare
  evt_id text;
begin
  if new.platform is null then return new; end if;
  evt_id := 'lead_' || new.id || '_lead';
  insert into public.ads_conversion_events_log
    (lead_id, platform, event_type, event_id, event_time)
  values (new.id, new.platform, 'Lead', evt_id, new.created_at)
  on conflict (platform, event_id) do nothing;
  return new;
end $$;

drop trigger if exists trg_queue_ads_conversion_on_new_lead on public.ads_leads;
create trigger trg_queue_ads_conversion_on_new_lead
  after insert on public.ads_leads
  for each row execute function public.queue_ads_conversion_on_new_lead();

insert into public.beithady_audit_log(module, action, metadata) values
  ('ads', 'conversion_events_installed',
   jsonb_build_object('migration', '0106_bh_ads_conversion_events', 'triggers', 2));
