alter table public.ads_campaigns add column if not exists negative_keywords text[];

create table if not exists public.ads_brand_protection_defaults (
  id              bigint generated by default as identity primary key,
  scope           text not null default 'global' check (scope in ('global','platform')),
  platform        text check (platform in ('meta','google','tiktok')),
  keywords        text[] not null default '{}',
  updated_at      timestamptz not null default now()
);

alter table public.ads_brand_protection_defaults enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='ads_brand_protection_defaults' and policyname='ads_brand_def_all') then
    create policy ads_brand_def_all on public.ads_brand_protection_defaults for all using (true) with check (true);
  end if;
end $$;

insert into public.ads_brand_protection_defaults (scope, platform, keywords) values
  ('global', null, ARRAY[
     'airbnb','booking.com','agoda','vrbo','expedia','hostelworld',
     'free','cheap','hostel','dorm','couchsurfing',
     'review','complaint','scam','refund',
     'jobs','careers','hiring',
     'wikipedia'
   ])
on conflict do nothing;

insert into public.ads_brand_protection_defaults (scope, platform, keywords) values
  ('platform', 'google', ARRAY[
     'beit hady review','beit hady airbnb','beit hady booking',
     'beit hady scam','beit hady complaint'
   ])
on conflict do nothing;

insert into public.beithady_audit_log(module, action, metadata) values
  ('ads', 'negative_keywords_installed',
   jsonb_build_object('migration', '0107_bh_ads_negative_keywords'));
