create table if not exists public.web_vitals (
  id          bigint generated by default as identity primary key,
  ts          timestamptz not null default now(),
  metric      text not null check (metric in ('CLS','FCP','FID','INP','LCP','TTFB')),
  value       numeric not null,
  rating      text check (rating in ('good','needs-improvement','poor')),
  path        text not null,
  building_code text,
  user_agent  text,
  navigation_type text,
  region      text
);
create index if not exists idx_web_vitals_metric_ts on public.web_vitals(metric, ts desc);
create index if not exists idx_web_vitals_path_ts on public.web_vitals(path, ts desc);

alter table public.web_vitals enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='web_vitals' and policyname='web_vitals_all') then
    create policy web_vitals_all on public.web_vitals for all using (true) with check (true);
  end if;
end $$;

insert into public.beithady_audit_log(module, action, metadata) values
  ('ads', 'web_vitals_installed', jsonb_build_object('migration', '0111_bh_web_vitals'));
