create table if not exists public.ads_lead_touches (
  id              bigint generated by default as identity primary key,
  lead_id         bigint references public.ads_leads(id) on delete cascade,
  phone_e164      text,
  platform        text not null check (platform in ('meta','google','tiktok','organic')),
  campaign_id     bigint references public.ads_campaigns(id) on delete set null,
  ad_id           bigint references public.ads_ads(id) on delete set null,
  touch_type      text not null check (touch_type in ('impression','click','message','form_submit')),
  utm_source      text,
  utm_campaign    text,
  utm_medium      text,
  utm_content     text,
  occurred_at     timestamptz not null default now(),
  raw             jsonb
);
create index if not exists idx_ads_touches_phone_time on public.ads_lead_touches(phone_e164, occurred_at desc);
create index if not exists idx_ads_touches_lead on public.ads_lead_touches(lead_id);

alter table public.ads_lead_touches enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='ads_lead_touches' and policyname='ads_touches_all') then
    create policy ads_touches_all on public.ads_lead_touches for all using (true) with check (true);
  end if;
end $$;

insert into public.ads_lead_touches (lead_id, phone_e164, platform, campaign_id, ad_id, touch_type, occurred_at)
select id, phone_e164, platform, campaign_id, ad_id, 'form_submit', created_at
  from public.ads_leads
 where not exists (select 1 from public.ads_lead_touches t where t.lead_id = ads_leads.id);

create or replace view public.ads_campaign_attribution_linear as
with booked_leads as (
  select l.id as lead_id, l.matched_reservation_id, r.host_payout, r.currency
    from public.ads_leads l
    join public.guesty_reservations r on r.id = l.matched_reservation_id
   where l.matched_reservation_id is not null
)
, touches_per_lead as (
  select t.lead_id, count(*) as touch_count
    from public.ads_lead_touches t
    join booked_leads bl on bl.lead_id = t.lead_id
   group by t.lead_id
)
select
  t.campaign_id,
  cp.name                         as campaign_name,
  cp.platform                     as platform,
  count(distinct t.lead_id)       as touched_bookings,
  sum(1.0 / tpl.touch_count)      as linear_credit,
  sum( (bl.host_payout) / tpl.touch_count ) as linear_revenue_native
from public.ads_lead_touches t
join booked_leads bl on bl.lead_id = t.lead_id
join touches_per_lead tpl on tpl.lead_id = t.lead_id
left join public.ads_campaigns cp on cp.id = t.campaign_id
where t.campaign_id is not null
group by t.campaign_id, cp.name, cp.platform;

insert into public.beithady_audit_log(module, action, metadata) values
  ('ads', 'multi_touch_installed', jsonb_build_object('migration', '0114_bh_ads_multi_touch'));
