-- supabase/migrations/0135_bh_marketing_reels.sql
-- BH Marketing Reels: display-in table for embedding curated public
-- social reels (TikTok first; Instagram-ready via the `platform` column)
-- inside /beithady/ads/tiktok/organic. No external API integration —
-- these are manually curated URLs rendered via TikTok's public embed.js.
--
-- Distinct from ads_tiktok_posts (migration 0103) which models the
-- publish-OUT flow through the TikTok Content Posting API. That flow
-- was blocked by TikTok dev-app rejection in May 2026; embed-in does
-- not need API access.

create table if not exists public.bh_marketing_reels (
  id            bigint generated by default as identity primary key,
  platform      text not null default 'tiktok'
                  check (platform in ('tiktok','instagram')),
  url           text not null,
  external_id   text not null,
  caption       text,
  building_code text,
  sort_order    int  not null default 0,
  is_visible    boolean not null default true,
  created_by    uuid references auth.users(id),
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  unique (platform, external_id)
);

create index if not exists bh_marketing_reels_visible_idx
  on public.bh_marketing_reels(is_visible, sort_order, created_at desc);

create index if not exists bh_marketing_reels_building_idx
  on public.bh_marketing_reels(building_code)
  where building_code is not null;

alter table public.bh_marketing_reels enable row level security;

do $$ begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename  = 'bh_marketing_reels'
      and policyname = 'bh_marketing_reels_all'
  ) then
    create policy bh_marketing_reels_all
      on public.bh_marketing_reels
      for all using (true) with check (true);
  end if;
end $$;
